### ISSUE TITLE
Install and setup latest Bootstrap

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#12]
**Description**

#### Tasks
- [x] Install latest version of [Bootstrap](https://getbootstrap.com/)
    - [x] Install `jquery@1.9.1` as `bootstrap@4.1.3` requires a peer dependencies.
    - [x] Install `popper.js@^1.14.3` as `bootstrap@4.1.3` requires a peer dependencies.
- [x] Setup custom SCSS file and import bootstrap SCSS file. (Universe.scss [Universe UI])

#### Install Bootstrap v4.1.3
```
npm install bootstrap
```
