### ISSUE TITLE
Migrate create react app from v2.0.0-next to v2.0.3

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#14]
#### Description
Migrate create react app from v2.0.0-next to v2.0.3

#### Latest version
https://github.com/facebook/create-react-app/releases/tag/v2.0.3

#### Migration instructions
- https://reactjs.org/blog/2018/10/01/create-react-app-v2.html
- https://gist.github.com/gaearon/8650d1c70e436e5eff01f396dffc4114

#### Tasks
- [x] Read through upgrade instructions
- [x] Upgrade using `npm install --save --save-exact react-scripts@2.0.3`
- [x] Replace `node-sass-chokidar` with `node-sass`
- [x] update dependencies

Next...
- [#16 Setup Bootstrap Sass theming](https://github.com/universelabs/universe.engineering/issues/16) to ensure everything is wired up.

#### References
- [Adding Sass](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-sass-stylesheet)
