### ISSUE TITLE
Apply favicon, Apple icons to React meta data

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#17]
**Description**
Apply favicon, Apple icons to React meta data

Tasks
- [x] favicon & touch icons
- [x] meta data in html
- [x] meta data in manifest.json

**Comment by guylepage3** [comment]
Meta data for React.js app

```
<!-- Place favicon.ico in the root directory -->
<link rel="shortcut icon" href="/favicon.ico?v=2">
<link rel="apple-touch-icon" sizes="29x29" href="/icons/universe-apple-touch-29.png" />
<link rel="apple-touch-icon" sizes="40x40" href="/icons/universe-apple-touch-40.png" />
<link rel="apple-touch-icon" sizes="58x58" href="/icons/universe-apple-touch-58.png" />
<link rel="apple-touch-icon" sizes="60x60" href="/icons/universe-apple-touch-60.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/icons/universe-apple-touch-76.png" />
<link rel="apple-touch-icon" sizes="80x80" href="/icons/universe-apple-touch-80.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/icons/universe-apple-touch-120.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/icons/universe-apple-touch-152.png" />
<link rel="apple-touch-icon" sizes="167x167" href="/icons/universe-apple-touch-167.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/icons/universe-apple-touch-180.png" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#000000">
```

**Comment by guylepage3** [comment]
`manifest.json` meta data for React.js app

```
universe-cluster-icon-rounded-48x48.png
universe-cluster-icon-rounded-72x72.png
universe-cluster-icon-rounded-96x96.png
universe-cluster-icon-rounded-128x128.png
universe-cluster-icon-rounded-256x256.png
universe-cluster-icon-rounded.svg
```
