### ISSUE TITLE
Refactor and restructure styles for reduced complexity

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#44]
**Description**
Refactor and restructure styles for reduced complexity and to match new component based styling.

Currently we are using a mixture of SCSS, CSS, inline and Styled Components for styling universe.engineering. Since Meta v1.5's new stand alone structure, we are now able to apply a more focused SCSS styling methodology, making it much easier to manage styles and contribute to the project.

**Tasks**
- [x] Create new SCSS component file structure.
- [x] Pull all CSS styles into SCSS component files.
- [x] Pull out all unnecessary inline styles.
- [x] Find all styles that can be consolidated and/or removed to reduce complexity and bloat.
- [x] Test.
- [x] Push live.

**Refactor Containers**
- [x] Contact.js
- [x] Home.js
- [x] MailerError.js
- [x] MailerSuccess.js
- [x] NoMatch.js
- [x] Roadmap.js
- [x] Subscribe.js
- [x] SubscribeError.js
- [x] SubscribeSuccess.js

**Refactor Components**
- [x] Code404.js
- [x] ContactForm.js
- [x] Footer.js
- [x] FooterColCenter.js
- [x] FooterColLeft.js
- [x] FooterColRight.js
- [x] Hero.js
- [x] Navbar.js
- [x] NavbarToggler.js
- [x] Social.js
- [x] SubscribeForm.js

**CSS Merge**
- [x] Animations.css
- [x] Buttons.css
- [x] Footer.css
- [x] Navbar.css
- [x] PatternLibrary.css
- [x] Subscribe.css

**Structure**
- [x] _alert.scss
- [x] _button-group.scss
- [x] _buttons.scss
- [x] _card.scss
- [x] _code.scss
- [x] › _components.scss
- [x] _custom-forms.scss
- [x] _dropdown.scss
- [x] › _forms.scss
- [x] _functions.scss
- [x] _grid.scss
- [x] _images.scss
- [x] _input-group.scss
- [x] _jumbotron.scss
- [x] _list-group.scss
- [x] ››› _meta-cts.scss
- [x] _mixins.scss
- [x] _nav.scss
- [x] _navbar.scss
- [x] _popover.scss
- [x] _reboot.scss
- [x] _root.scss
- [x] _tables.scss
- [x] _tooltip.scss
- [x] _transitions.scss
- [x] _type.scss
- [x] _utilities.scss
- [x] _variables.scss
- [x] mixins/_media-queries.scss
- [x] universe.scss

**Comment by guylepage3** [comment]
New SCSS design

```text
scss/
├── _alert.scss
├── _button-group.scss
├── _buttons.scss
├── _card.scss
├── _code.scss
├── _components.scss
├── _custom-forms.scss
├── _dropdown.scss
├── _forms.scss
├── _functions.scss
├── _grid.scss
├── _images.scss
├── _input-group.scss
├── _jumbotron.scss
├── _list-group.scss
├── _meta-cts.scss
├── _mixins.scss
├── _nav.scss
├── _navbar.scss
├── _popover.scss
├── _reboot.scss
├── _root.scss
├── _tables.scss
├── _tooltip.scss
├── _transitions.scss
├── _type.scss
├── _utilities.scss
├── _variables.scss
├── mixins/
|   └── _media-queries.scss
└── universe.scss // Custom styles for the project and/or brand
```

**Comment by guylepage3** [comment]
Testing

**Comment by guylepage3** [comment]
`*-editorial` classes are being overridden.

Possible solution.. pull classes out of `_type-scaling.scss` and place them in as utility styles.

**Comment by guylepage3** [comment]
Done

**Comment by guylepage3** [comment]
Done
