### ISSUE TITLE
Build quick and dirty POC

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#46]
**Description**
Build quick and dirty POC.

This initial POC's goal is just to show what the UX could be like for users. No auth, nothing fancy at all.

**User flow for POC**
1. User goes to universe.engineering/testnet
2. Sign up form (metamask-like)
3. User's taken to dashboard
4. User sees private key
5. User can click to copy to clipboard

**Tasks**
- [x] [Design quick and dirty POC](https://github.com/universelabs/universe-design/issues/17).
- [ ] Build POC components.
  - [x] Navbar (light).
    - [x] Navbar toggler (dark).
  - [x] Sign up page / form
  - [x] Dashboard
  - [ ] Dashboard w/ clicked copy to clipboard
- [x] Live design Sign up page.
- [x] Build out React route.
- [ ] Live design dashboard containing a number of keys & passphrases.
- [ ] Add click to copy to clipboard functionality. See [Comment](https://github.com/universelabs/universe.engineering/issues/46#issuecomment-488315117)
- [ ] Create screen share video.

**Corresponding Issues**
- [x] [#54 Adjust layout on sign-up page on mobile](https://github.com/universelabs/universe.engineering/issues/54)

**Reference**
- universelabs/universe-operations#9 Define strategy for key management software POC

**Comment by guylepage3** [comment]
Also see [#50 Updates to the User Flow for POC](https://github.com/universelabs/universe.engineering/issues/50)

**Comment by guylepage3** [comment]
Use the `copy-to-clipboard` npm package. https://www.npmjs.com/package/copy-to-clipboard

**Comment by guylepage3** [comment]
Closing issue
