### ISSUE TITLE
Updates to the User Flow for POC

### ISSUE THREAD

**Issue by aseoconnor** [universelabs/universe.engineering#50]
**Description**
When a user goes to https://universe.engineering/sign-up we should modify the UX slightly:

**Tasks**
- [x] On /sign-up we should remove: "Continue to quickly sign up on all major blockchains.", "username", and "passphrase" 
- [x] On /sign-up we should add a link in the footer for Terms
- [ ] On /dashboard when you click on any of the blockchains it should show you the seedphrase // wallet address
- [ ] On /dashboard we should create the ability to **add a new blockchain**. Users should be able to "Create New Accounts" or "Add existing".  Create New should populate a list of all of the blockchains they can add. Add Existing should let them choose which blockchain and then add in their seed phrase

Any other information you want to share that is relevant to the issue. This might include the lines of code, screenshots, imagery, links, solutions, opinions, feedback, etc.
