### ISSUE TITLE
Live design v1.0.0

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#7]
**Description**
Live design v1.0.0 of website

#### Tasks
- [x] Full page cover wrapper
- [x] Create `Hero.js` component
  - [x] `h1`
  - [x] `lead`
- [x] Center hero content in window
- [x] Animate hero content
- [x] `Header.js` component
  - [x] `Image.js` component
  - [x] Add SVG logo
- [x] Create dApp developer questionnaire
- [x] Add button to questionnaire
  - [x] Hide Hero button on mobile
- [x] `Footer.js` component

**Comment by guylepage3** [comment]
Done
