### ISSUE TITLE
Refactor & move client (universe.engineering) to DigitalOcean

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#71]
**Description**
Refactor & move client (universe.engineering) from Heroku to DigitalOcean.

Heroku requires a static IP in order to configure a root domain. We, at Universe, must configure our DNS to root as we cannot have our apps resolving to `www.universe.engineering`. Our DNS must resolve to `universe.engineering` as our TLD is so long and confusing for folks. we’ve received a lot of feedback on this issue.

The catch is that Heroku requires a static IP configuration and Heroku is the only hosting provider out there that does not work with `A records` for root domains.

Heroku’s solution is to use dnsimple.com for aliasing. they have worked with them to provide this service.

So technically, we need to get off DNSimple.com but since we need to resolve to a root domain, we now need to move off of Heroku.

**Tasks**
- [x] Determine whether we should move to ~~Netlify~~ or ~~GCP~~ or ✅DigitalOcean.
- [x] ~~[#56 Understand how to run node.js apps on VM's](https://github.com/universelabs/universe/issues/56)~~
- [ ] Setup app on DigitalOcean.
- [ ] Test deployments on new provider.
- [ ] Delete app from Heroku.

**References**
- [Add a custom root domain: Heroku](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain)
- [Full Node.js Deployment - NGINX, SSL With Lets Encrypt](https://youtu.be/oykl1Ih9pMg)

**Comment by guylepage3** [comment]
@faddat let me know if you need anything here. I am happy to walk you through Heroku.

**Comment by guylepage3** [comment]
Great work on this so far @faddat.. Pegging NGINX issue to this one.

**Comment by guylepage3** [comment]
@faddat I just added [Full Node.js Deployment - NGINX, SSL With Lets Encrypt](https://youtu.be/oykl1Ih9pMg) to the references list. I'll go through this tutorial in the morning and apply it to the app.

**Comment by guylepage3** [comment]
Taking over this issue.
