### ISSUE TITLE
DKIM email issue

### ISSUE THREAD

**Issue by faddat** [universelabs/universe.engineering#72]
**Description**
Today we had a nasty DKIM issue!  We did not have DKIM in our DNSimple, which was causing our mail to go directly to people's spam.  

**Tasks**
- [x] Generate DKIM record on Google from the Admin panel at admin.google.com (Must be Super-admin)
- [x] Put DKIM record in DNSSimple as a TXT record
- [x] Test DKIM record - [Is Not Spam](http://isnotspam.com/)

We fixed it by generating a DKIM key on Google's admin panel, and adding that to our Netlify DNS settings.  

**DKIM Definition**
DKIM (DomainKeys Identified Mail) is a method to validate the authenticity of email messages. When each email is sent, it is signed using a private key and then validated on the receiving mail server (or ISP) using a public key that is in DNS. This process verifies that the message was not altered during transit.

**Links**
[Setup DKIM to Prevent E-mail Spoofing](https://support.google.com/a/answer/174124)
[Generate a DKIM key for your domain](https://support.google.com/a/answer/174126)
