### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#74]
**Description**
Update dependencies. Update npm. npm update. Using `ncu` or `npm-check-updates`.

**Tasks**
- [x] Run `$ ncu` on root directory and client.
- [x] Run `$ ncu -u` on root directory and client.
- [x] Run `$ npm install` on root directory and client.
- [x] Follow instructions.

**References**
- [npm-check-updates on npmjs.com](https://www.npmjs.com/package/npm-check-updates)
