### ISSUE TITLE
Build Slack invite form / express server

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#75]
**Description**
Build Slack invite form / express server for easy invite link change as Slack may cancel our link again. This will allow us to make one simple change instead of 20.

**Tasks**
- [x] Research the best method for building out form
- [x] Generate Slack token
- [x] Add [reCAPTCHA](https://www.google.com/recaptcha/intro/v3.html)
- [x] Deploy app to Heroku

**NOTE**
SLACK_SUBDOMAIN is only the `universelabs`. not `universelabs.slack.com`.

**References**
- [npm Slackin](https://www.npmjs.com/package/slackin)
- [Slackin (GitHub)](https://github.com/rauchg/slackin)

**Comment by guylepage3** [comment]
Done. https://universelabs-slackin.herokuapp.com/

**Comment by guylepage3** [comment]
@faddat i’ve set us up with a new “slack” invitation page with recaptcha so that we can onboard users easier as well as not have to worry about the slack invite links disappearing.

https://universelabs-slackin.herokuapp.com

Can i get you to redirect this to https://slack.universe.engineering?
