### ISSUE TITLE
Pull out Mailchimp Express server for Digital Ocean migration

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#77]
**Description**
As a result of migrating to a VM, we should pull the Mailchimp (subscribe) Express server out of the web app so that we can run them individual, separate services.

**Tasks**
- [x] Create new repository.
- [x] Setup Express server.
- [x] Add config files.

**Comment by guylepage3** [comment]
Not sure we need to do this actually. Loads of articles on deploying node.js / react apps to digital ocean.

**Comment by guylepage3** [comment]
Reopening this issue.

**Comment by guylepage3** [comment]
Done.
