### ISSUE TITLE
Setup new website client

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#78]
**Description**
As a result of migrating to a VM, we need to pull the Express server out of the web app so that we can run them on separate machines and to simplify things we will create a new web client.

**Tasks**
- [ ] Create new repository.
- [ ] Setup new web client.
- [ ] Wire up web app to Express server #77.
- [ ] Test for CORS issues.
