### ISSUE TITLE
Review & decide which service splitting method is fastest

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#79]
**Description**
Review & decide which service splitting method is fastest.

**Tasks**
- [x] Review service split to run multiple back-end instances, Mailchimp & Nodemailer.
- [x] Review service split to run a single express.js back-end instance for both Mailchimp & Nodemailer.
- [x] ~~@faddat to confirm with @guylepage3 which method to execute.~~ @guylepage3 @faddat decided to go with individual services.

**Comment by guylepage3** [comment]
@guylepage3 @faddat decided to go with individual services.

**Comment by guylepage3** [comment]
Done
