### ISSUE TITLE
Pull out Nodemailer Express server for Digital Ocean migration

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#81]
**Description**
As a result of migrating to a VM, we should pull the Nodemailer (sendEmail) Express server out of the web app so that we can run them individual, separate services.

**Tasks**
- [x] Create new repository.
- [x] Setup Express server.
- [x] Add config files.
- [x] Run server for testing.

**Comment by guylepage3** [comment]
Done
